language: C

install:
  - travis_wait 30 ./setup/travis_install.sh lsst-sims nose pandas pylint
  - ln -sf /home/travis/miniconda/lib/libssl.so.1.0.0 /home/travis/miniconda/lib/libssl.so.10
  - ln -sf /home/travis/miniconda/lib/libcrypto.so.1.0.0 /home/travis/miniconda/lib/libcrypto.so.10
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - pip install coveralls
  - setup lsst_sims
  - eups declare -r . pserv -t current
  - setup pserv

cache:
  directories:
  - $HOME/miniconda.tarball
  timeout: 360

services:
  - mysql

before_script:
  - mysql -e 'create database myapp_test'
  - mysql -e 'show databases;'
  - mkdir /home/travis/.lsst
  - cp tests/db-auth.paf /home/travis/.lsst/db-auth.paf
  - chmod 700 /home/travis/.lsst
  - chmod 600 /home/travis/.lsst/db-auth.paf

script:
  - nosetests -s --with-coverage --cover-package=desc.pserv
  - pylint --py3k `find . -name \*.py -print`

after_success:
  - coveralls
